### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by PervinHesenov105** [PervinHesenov105/JavaMen#3]
1. instagram sehifesinden elaqe melumatlarini elave et 
2. srift san-serif olsun
3. birbasa skype call olsun 
4. xerite 3:4 miqyasinda olsun

**Comment by PervinHesenov105** [comment]
mutleq version1 branchina elave et

**Comment by vasifrahimli** [comment]
task hazirdir

**Comment by PervinHesenov105** [comment]
cox sagol
